Review
Oodmincheg/movie-db pull request #3
Opened 2018-12-10 17:00 UTC by Oodmincheg

[Demo](https://oodmincheg.github.io/movie-db/)
[Task](https://gist.github.com/krambertech/ecb3890824fd7ada0f4ec1ff55125758)
[Code](https://github.com/Oodmincheg/movie-db/tree/master/src)

2018-12-10 20:02 UTC, zonzujiro requested changes
Great job!

Now try to add some tests, remove the commented part and see comments.

Also, you have 404 if I refresh a page on the movie screen or on a watch list.

And - where is redux? 🤔

2018-12-10 20:02 UTC, zonzujiro commented on js/AddWatchListButton.js
> +    localStorage.removeItem(this.props.id);
Usually, you don't need to put something into `localStorage` so often. You can do this in lifecycle methods:
1. Take from `localStorage` and put to the state in the constructor or `componentDidMount`
2. Take from state and put to `localStorage` in `componentWillUnmount`

Between this two steps you work with the state, not with `localStorage`

2018-12-10 20:02 UTC, zonzujiro commented on js/AddWatchListButton.js
> +  constructor(props) {
FYI, you can use class properties instead constructor and binding:

```javascript
state = {
  inWatchList: true
}

deleteFromWatchList = () => {}
```

But you should know the difference ;)

2018-12-10 20:02 UTC, zonzujiro commented on js/App.js
> +              render={() => <PopularMovies movies={this.state.popularMovies} />}
```javascript
const { popularMovies } = this.state
```

 etc. 😄

2018-12-10 20:02 UTC, zonzujiro commented on js/App.js
> +        <BrowserRouter basename={process.env.PUBLIC_URL}>
What if you will have a larger amount of routes? I mean, 12 or 20? Try to put routes into a different file.

2018-12-10 20:02 UTC, zonzujiro commented on js/MovieCard.js
> +class MovieCard extends React.Component {
In a case when you don't need state, you can use functional components :)

2018-12-10 20:02 UTC, zonzujiro commented on js/MovieCard.js
> +        <Image src={this.props.imgSrc} alt={this.props.title} />
Same here, extract values from props to variables.

2018-12-10 20:02 UTC, zonzujiro commented on js/MoviePage.js
> +      .then(res => res.json())
I think you should put fetch logic to a different file and then call something like `getMoviewDetails`.

Also, fill free to use `async/await`.
Also, you should handle errors in fetch [properly](https://www.tjvantoll.com/2015/09/13/fetch-and-errors/)

2018-12-10 20:02 UTC, zonzujiro commented on js/PopularMovies.js
> +  fetchMoreData() {
`fetchMoreData` is a bad naming, because there is not understanding what data you want to load.

2018-12-10 20:02 UTC, zonzujiro commented on js/PopularMovies.js
> +            hasMore={true}
Always `true`? 🤔 

Also, boolean props can be passed simply like this: `<InfinteScroll hasMore next={...}`

You don't need `true` here

2018-12-10 20:02 UTC, zonzujiro commented on js/PopularMovies.js
> +                .filter(movie =>
Well... you should know, that such code will create a new function on every render. While in general, this is [ok](https://reactjs.org/docs/faq-functions.html#is-it-ok-to-use-arrow-functions-in-render-methods), but not for everyone 😄 So be wise with it.

2018-12-10 20:02 UTC, zonzujiro commented on js/PopularMovies.js
> +                    title={movie.title}
Can you replace it with `<MovieCard {...movie}` or `<MovieCard movie={movie}`?

You getting a lot of values from `movie` object. Looks like you need almost all of them.

2018-12-10 20:02 UTC, zonzujiro commented on js/WatchList.js
> +    for (let i = 0; i < localStorage.length; i++) {
`localStorage.length`

![img](https://i.imgur.com/IppKJ.jpg)

How your code will work if I will add more values to `localStorage`? I mean, another developer. This construction is very fragile.

2018-12-10 20:02 UTC, zonzujiro commented on js/WatchList.js
> +    if (localStorage.length === 0) {
👀

2018-12-11 13:44 UTC, Oodmincheg commented on js/AddWatchListButton.js
> +  constructor(props) {
I know, that I can. But I don't know a difference, I thought that is just a "sugar" for constructor and binding. But now I think that I just lack of knowledge :) Can you give me maybe hint or link? I read this article https://michalzalecki.com/react-components-and-class-properties/, but haven't figure out the difference except syntax(it's not about syntax, right?)

2018-12-11 13:58 UTC, Oodmincheg commented on js/PopularMovies.js
> +                    title={movie.title}
Yes I can. But it's interesting to me is this the for readability or something like this?

2018-12-11 13:59 UTC, Oodmincheg commented on js/MovieCard.js
> +        <Image src={this.props.imgSrc} alt={this.props.title} />
I always should dot this? Is this about readability or maybe it can be cause for mutations in some way?

2018-12-11 14:00 UTC, Oodmincheg commented on js/App.js
> +              render={() => <PopularMovies movies={this.state.popularMovies} />}
Add question below.

2018-12-12 10:25 UTC, zonzujiro commented on js/MovieCard.js
> +        <Image src={this.props.imgSrc} alt={this.props.title} />
Readability. Which is a good point :)

2018-12-12 10:45 UTC, zonzujiro commented on js/AddWatchListButton.js
> +  constructor(props) {
Right, it is not *only* about syntax.

Long story short - you can't access class properties from an instance of the class. So something like:

```
const component = new WatchListButton();
component.deleteFromWatchList()
```

Will not work.

2019-01-11 12:11 UTC, Oodmincheg commented on js/PopularMovies.js
> +            hasMore={true}
I need. This api of this InfiniteScroll(without `true` doesn't work, i've cheked)

2019-12-18 12:44 UTC, closed without merging